### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by noahcui** [junyang/radb#7]
SQLAlchemy recently released 2.0.0 which radb doesn't work with. The latest version that works:

SQLAlchemy==1.4.46

Installing radb will install the latest version by default, so you may need to downgrade SQLAlchemy to 1.4.46 after installation.

**Comment by onrcn** [comment]
Current release of antlr4-python3-runtime (4.12.0 as I'm writing this) doesn't work with radb too. The version that works for me is:
antlr4-python3-runtime==4.9.3

**Comment by junyang** [comment]
Thanks for spotting these problems. I will upgrade soon!

**Comment by junyang** [comment]
Should be fixed in 3.0.5 now.
